version: '3.8'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codepushdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  # MySQL running on localhost:3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Redis running on localhost:6379

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"  # LocalStack running on localhost:4566

volumes:
  db_data:
